services:
  bearer-auth-service:
    build: .
    image: bearer-auth-service:latest
    container_name: bearer-auth-service
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/var/logs/bearer-auth-service
    ports:
      - "8080:${PORT}"